return {
	the_all_seeing_eye = "",
	the_not_so_all_seeing_eye = "",
	error_symbol = "󰈸",
	warning_symbol = "󰞴",
	hint_symbol = "",
	info_symbol = "",
	modified_symbol = "",
	readonly_symbol = "󰌾",
	unnamed_symbol = "",
	newfile_symbol = "",
	git_add_symbol = "┃",
	git_change_symbol = "┃",
	git_delete_symbol = "_",
	git_topdelete_symbol = "‾",
	git_changedelete_symbol = "~",
	git_untracked_symbol = "┆",
}
