#!/usr/bin/env python3

from subprocess import check_output
import os
import re

config = dict(os.environ)
current_brightness = check_output(["brightnessctl", "g"], universal_newlines=True)
max_brightness = check_output(["brightnessctl", "m"], universal_newlines=True)
output = ""

if not max_brightness:
    # not good!!!!!!!
    output = "<span>Err: no max</span>"
if not current_brightness:
    # not good!!!!!!
    output = "<span>Err: no cur</span>"
else:
    output = "<span>󰖨  {:.0f}</span>".format(
        (int(current_brightness) / int(max_brightness)) * 100
    )
print(output)
if not max_brightness or not current_brightness:
    exit(33)

