#!/usr/bin/env bash

if [[ -z "$INTERFACE" ]] ; then
   INTERFACE="${BLOCK_INSTANCE:-wlan0}"
fi

COLOUR_GE80=${COLOUR_GE80:-#9cd57b}
COLOUR_GE60=${COLOUR_GE60:-#f3a96a}
COLOUR_GE40=${COLOUR_GE40:-#e3d367}
COLOUR_LOWR=${COLOUR_LOWR:-#f76c7c}
COLOUR_DOWN=${COLOUR_DOWN:-#f76c7c}

# If no interface, show nothing
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] && exit

# If interface but no active connection, display "down"
if [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]]; then
   echo "down" # full text
   echo "down" # short text
   echo $COLOUR_DOWN # colour
   exit
fi

# Get SSID
SSID=$(iw "$INTERFACE" info | awk '/ssid/ {$1=""; print $0}')

# Get quality
QUALITY=$(iw dev ${INTERFACE} link | grep 'dBm$' | grep -Eoe '-[0-9]{2}' | awk '{print ($1 > -50 ? 100 :($1 < -100 ? 0 : ($1+100)*2))}')

# Output
echo "$SSID: $QUALITY%" # full text
echo "$QUALITY%" # short text
if [[ $QUALITY -ge 80 ]]; then
   echo $COLOUR_GE80
elif [[ $QUALITY -ge 60 ]]; then
   echo $COLOUR_GE60
elif [[ $QUALITY -ge 40 ]]; then
   echo $COLOUR_GE40
else
   echo $COLOUR_LOWR
fi # colour
